/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TutorProfile as PrismaTutorProfile } from "@prisma/client";

export class TutorProfileServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TutorProfileCountArgs, "select">
  ): Promise<number> {
    return this.prisma.tutorProfile.count(args);
  }

  async tutorProfiles(
    args: Prisma.TutorProfileFindManyArgs
  ): Promise<PrismaTutorProfile[]> {
    return this.prisma.tutorProfile.findMany(args);
  }
  async tutorProfile(
    args: Prisma.TutorProfileFindUniqueArgs
  ): Promise<PrismaTutorProfile | null> {
    return this.prisma.tutorProfile.findUnique(args);
  }
  async createTutorProfile(
    args: Prisma.TutorProfileCreateArgs
  ): Promise<PrismaTutorProfile> {
    return this.prisma.tutorProfile.create(args);
  }
  async updateTutorProfile(
    args: Prisma.TutorProfileUpdateArgs
  ): Promise<PrismaTutorProfile> {
    return this.prisma.tutorProfile.update(args);
  }
  async deleteTutorProfile(
    args: Prisma.TutorProfileDeleteArgs
  ): Promise<PrismaTutorProfile> {
    return this.prisma.tutorProfile.delete(args);
  }
  async FindTutorsByLocation(args: string): Promise<string> {
    throw new Error("Not implemented");
  }
  async RegisterTutor(args: string): Promise<string> {
    throw new Error("Not implemented");
  }
}
